import Algorithms

public struct CodeGenerator {
    private let renderNodes: [RenderNode]
    private let parameters: [Parameter]
    private let sourceFile: String
    private let filename: String
    private let emitSourceLocations: Bool

    public init(
        renderNodes: [RenderNode],
        parameters: [Parameter],
        sourceFile: String,
        filename: String,
        emitSourceLocations: Bool = true
    ) {
        self.renderNodes = renderNodes
        self.parameters = parameters
        self.sourceFile = sourceFile
        self.filename = filename
        self.emitSourceLocations = emitSourceLocations
    }

    /// Returns a self-contained immediately-invoked closure expression that
    /// builds and returns the rendered template buffer.
    public func generateExpression() -> String {
        var lines: [String] = []
        lines.append("{")
        lines.append("    var _buf = ESWBuffer()")
        let emittedLocation = emitNodeBody(&lines, nodes: renderNodes)
        if emitSourceLocations && emittedLocation {
            lines.append("    #sourceLocation()")
        }
        lines.append("    return _buf.finalize()")
        lines.append("}()")
        return lines.joined(separator: "\n")
    }

    public func generate() -> String {
        var lines: [String] = []

        lines.append("// AUTO-GENERATED by swift-esw. DO NOT EDIT.")
        lines.append("// Source: \(sourceFile)")
        lines.append("")

        // Always import ESW
        lines.append("import ESW")

        // Detect and add framework-specific imports based on parameter types
        let requiredImports = detectRequiredImports(from: parameters)
        for importName in requiredImports.sorted() {
            lines.append("import \(importName)")
        }

        lines.append("")

        generateStringFunction(&lines)

        return lines.joined(separator: "\n") + "\n"
    }

    private func generateStringFunction(_ lines: inout [String]) {
        let funcName = Naming.functionName(from: filename)
        let paramList = buildParamList()
        if paramList.isEmpty {
            lines.append("func \(funcName)() -> String {")
        } else {
            lines.append("func \(funcName)(")
            lines.append("    \(paramList)")
            lines.append(") -> String {")
        }
        lines.append("    var _buf = ESWBuffer()")
        let emittedLocation = emitNodeBody(&lines, nodes: renderNodes)
        if emitSourceLocations && emittedLocation {
            lines.append("#sourceLocation()")
        }
        lines.append("    return _buf.finalize()")
        lines.append("}")
    }

    private func buildParamList() -> String {
        return parameters.map { param in
            let swiftKey = param.name.split(separator: "-", omittingEmptySubsequences: false).joined(separator: "_")
            let escapedKey = CodeGenerator.escapedParamName(swiftKey)
            let type = param.type.split(separator: " ").first.map(String.init) ?? param.type
            if let defaultValue = param.defaultValue {
                return "\(escapedKey): \(type) = \(defaultValue)"
            } else {
                return "\(escapedKey): \(type)"
            }
        }.joined(separator: ", ")
    }

    @discardableResult
    private func emitNodeBody(_ lines: inout [String], nodes: [RenderNode], bufferName: String = "_buf") -> Bool {
        var emittedLocation = false
        for node in nodes {
            switch node {
            case .token(let token):
                if emitTokenBody(&lines, token: token, bufferName: bufferName) { emittedLocation = true }
            case .component(let componentNode):
                if emitComponentNode(&lines, node: componentNode, bufferName: bufferName) { emittedLocation = true }
            }
        }
        return emittedLocation
    }

    @discardableResult
    private func emitComponentNode(_ lines: inout [String], node: ComponentNode, bufferName: String) -> Bool {
        var emittedLocation = false
        if emitSourceLocation(lines: &lines, node.metadata) { emittedLocation = true }

        let typeName = kebabToPascalCase(node.name)

        // 1. Build argument list (attributes + named slots)
        var argParts: [String] = []

        // Attributes first
        argParts.append(contentsOf: node.attributes.map { attr in
            let swiftKey = attr.key.split(separator: "-", omittingEmptySubsequences: false).joined(separator: "_")
            switch attr.value {
            case .none: return "\(swiftKey): true"
            case .string(let s): return "\(swiftKey): \(rawStringLiteral(s))"
            case .expression(let expr): return "\(swiftKey): \(expr)"
            }
        })

        // Named slots (alphabetical)
        let sortedSlots = node.namedSlots.sorted { $0.name < $1.name }
        for slot in sortedSlots {
            let swiftKey = slot.name.split(separator: "-", omittingEmptySubsequences: false).joined(separator: "_")
            argParts.append("\(swiftKey): {")
            argParts.append("    var _buf = ESWBuffer()")
            emitNodeBody(&lines, nodes: slot.nodes, bufferName: "_buf")
            argParts.append("    return _buf.finalize()")
            argParts.append("}()")
        }

        // Content slot (last, if not empty)
        if !node.defaultSlot.isEmpty {
            argParts.append("content: {")
            argParts.append("    var _buf = ESWBuffer()")
            emitNodeBody(&lines, nodes: node.defaultSlot, bufferName: "_buf")
            argParts.append("    return _buf.finalize()")
            argParts.append("}()")
        }

        let finalArgList = argParts.joined(separator: ", ")

        lines.append("    \(bufferName).appendUnsafe(\(typeName).render(\(finalArgList)))")

        return emittedLocation
    }

    @discardableResult
    private func emitTokenBody(_ lines: inout [String], token: Token, bufferName: String = "_buf") -> Bool {
        var emittedLocation = false
        switch token {
        case .text(let s, let meta):
            if !s.isEmpty {
                // Only emit source location for single-line text to avoid breaking multiline string literals
                if !s.contains("\n") {
                    if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
                }
                if s.contains("\n") {
                    let h = rawStringHashes(s)
                    lines.append("    \(bufferName).append(\(h)\"\"\"\n\(s)\n\"\"\"\(h))")
                } else {
                    lines.append("    \(bufferName).append(\(rawStringLiteral(s)))")
                }
            }
        case .output(let expr, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(bufferName).appendEscaped(\(expr))")
        case .rawOutput(let expr, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(bufferName).appendUnsafe(\(expr))")
        case .code(let code, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            lines.append("    \(code)")
        case .comment, .assigns, .componentClose, .slotOpen, .slotClose:
            break
        case .componentTag(let name, let attributes, let selfClosing, let meta):
            if emitSourceLocation(lines: &lines, meta) { emittedLocation = true }
            let typeName = kebabToPascalCase(name)
            let argList = buildComponentArgList(attributes)
            if selfClosing {
                lines.append("    \(bufferName).appendUnsafe(\(typeName).render(\(argList)))")
            } else {
                lines.append("    \(bufferName).appendUnsafe(\(typeName).render(\(argList)))")
            }
        }
        return emittedLocation
    }

    // MARK: - Component helpers

    private func kebabToPascalCase(_ name: String) -> String {
        name.split(separator: "-", omittingEmptySubsequences: true)
            .map { segment -> String in
                let s = String(segment)
                guard let first = s.first else { return s }
                return first.uppercased() + s.dropFirst()
            }
            .joined()
    }

    private func buildComponentArgList(_ attributes: [ComponentAttribute]) -> String {
        attributes.map { attr in
            let swiftKey = attr.key.split(separator: "-", omittingEmptySubsequences: false).joined(separator: "_")
            switch attr.value {
            case .none:
                return "\(swiftKey): true"
            case .string(let s):
                return "\(swiftKey): \(rawStringLiteral(s))"
            case .expression(let expr):
                return "\(swiftKey): \(expr)"
            }
        }.joined(separator: ", ")
    }

    // MARK: - Private helpers

    private func detectRequiredImports(from parameters: [Parameter]) -> Set<String> {
        var imports = Set<String>()
        for param in parameters {
            // Check type annotations for known framework types
            if param.type.contains("Connection") {
                imports.insert("Nexus")
            }
            // Add more framework type detections as needed
            // For example: Peregrine, Hummingbird, Vapor, etc.
        }
        return imports
    }

    private func rawStringHashes(_ s: String) -> String {
        var hashes = 1
        while s.contains("\"" + String(repeating: "#", count: hashes)) ||
              s.contains(String(repeating: "#", count: hashes) + "\"") {
            hashes += 1
        }
        while s.contains("\"\"\"" + String(repeating: "#", count: hashes)) {
            hashes += 1
        }
        return String(repeating: "#", count: hashes)
    }

    private func rawStringLiteral(_ s: String) -> String {
        let h = rawStringHashes(s)
        return "\(h)\"\(s)\"\(h)"
    }

    private static let swiftKeywords: Set<String> = [
        "class", "struct", "enum", "protocol", "func", "var", "let",
        "import", "return", "if", "else", "for", "while", "switch",
        "case", "default", "break", "continue", "in", "is", "as",
        "self", "Self", "true", "false", "nil", "try", "catch",
        "throw", "throws", "guard", "where", "init", "deinit",
        "extension", "subscript", "operator", "typealias",
    ]

    static func escapedParamName(_ name: String) -> String {
        swiftKeywords.contains(name) ? "`\(name)`" : name
    }

    @discardableResult
    private func emitSourceLocation(lines: inout [String], _ meta: Metadata) -> Bool {
        guard emitSourceLocations else { return false }
        lines.append("#sourceLocation(file: \"\(meta.file)\", line: \(meta.line))")
        return true
    }
}